services:
  backend:
    build: backend
    container_name: backend
    volumes:
      - ./backend:/app/backend
    ports:
      - 5000:5000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
