services:
  backend:
    build: backend
    volumes:
      - ./backend:/usr/backend
      - /app/data
    ports:
      - 5000:5000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
