services:
  backend:
    build: backend
    container_name: backend
    volumes:
      - ./backend:/app/backend
      - /app/data
    ports:
      - 5000:5000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  frontend:
    build: frontend
    container_name: frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 8050:8050
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
