services:
  backend:
    build: backend
    container_name: backend
    volumes:
      - ./backend:/app/backend
      - /app/data
    ports:
      - 8888:8888
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8888

  frontend:
    build: frontend
    container_name: frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 8050:8050
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
